### ISSUE TITLE
Fix routing function

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#190]
12.	Routing.  
1.	What is the difference between route finder IN VIEW and route finder offline? 
2.	Why is there a lookup button on one but not the other? 
3.	Find route from A to anywhere doesn’t bring anything up.  Once it does, it’s going to need a BIG explanation.  I’m ok with that, just plan on it.  

In view is just the stars on the screen. I used to have a type ahead 
Offline is the entire dataset (which can take a lot of time if you pick a region with lots of star between them

The reason for why there is a lookup button for the offline is that you can enter a partial string and get a set of partial matches, then pick the one you actually want the reason for the no lookup is that I have a typeahead and partially disabled it until I worked out some problems. Then I forgot yo reconnect. Will put it back

This came out of one of the conversations with Chuck. I actually forget what was supposed to go here (since we don’t have any written requirements  )
I’ll remove it

**Comment by ljramones** [comment]
fixed and removed inactive functions

**Comment by cegannon1** [comment]
One thing. We *did* have written requirements. That's how we started things in the first Slack iteration. Documents with requirements.were sent and still exist if you need them again.

 But we are now at a level of detail that would never have been in any requirements I could have imagined or written. To many of these items are arising from specific directions that this program has taken that calm at least for me, or completely unforeseeable and completely beyond my comprehension both then and now.

But the basic requirements of what the program was to doThe ones that still really concern me, have been there from the start. I can Find and resend if you wish

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
